begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_agro00" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_agro10" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_agro20" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_agro30" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_agro40" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_agro50" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_forreg30" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_forreg40" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_forreg50" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_natveg00" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_natveg10" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_natveg20" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_natveg30" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_natveg40" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_natveg50" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_nonprodq00" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_nonprodq10" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_nonprodq20" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_nonprodq30" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_nonprodq40" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_nonprodq50" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_notrel00" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_notrel10" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_notrel20" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_notrel30" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_notrel40" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_notrel50" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_pltfor00" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_pltfor10" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_pltfor20" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_pltfor30" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_pltfor40" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_pltfor50" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_wetlnd00" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_wetlnd10" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_wetlnd20" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_wetlnd30" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_wetlnd40" numeric;commit;
begin;alter table "output_brazilsforestcode_states" add column if not exists "fcnocranosfa_wetlnd50" numeric;commit;

begin;update "output_brazilsforestcode_states" set "fcnocranosfa_agro00" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_agro10" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_agro20" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_agro30" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_agro40" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_agro50" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_forreg30" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_forreg40" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_forreg50" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_natveg00" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_natveg10" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_natveg20" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_natveg30" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_natveg40" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_natveg50" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_nonprodq00" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_nonprodq10" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_nonprodq20" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_nonprodq30" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_nonprodq40" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_nonprodq50" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_notrel00" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_notrel10" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_notrel20" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_notrel30" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_notrel40" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_notrel50" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_pltfor00" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_pltfor10" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_pltfor20" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_pltfor30" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_pltfor40" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_pltfor50" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_wetlnd00" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_wetlnd10" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_wetlnd20" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_wetlnd30" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_wetlnd40" = 0.0;commit;
begin;update "output_brazilsforestcode_states" set "fcnocranosfa_wetlnd50" = 0.0;commit;
