begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_agro00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_agro10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_agro20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_agro30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_agro40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_agro50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_forreg30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_forreg40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_forreg50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_natveg00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_natveg10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_natveg20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_natveg30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_natveg40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_natveg50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_nonprodq00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_nonprodq10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_nonprodq20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_nonprodq30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_nonprodq40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_nonprodq50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_notrel00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_notrel10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_notrel20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_notrel30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_notrel40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_notrel50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_pltfor00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_pltfor10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_pltfor20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_pltfor30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_pltfor40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_pltfor50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_wetlnd00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_wetlnd10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_wetlnd20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_wetlnd30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_wetlnd40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcdd_wetlnd50" numeric;commit;

begin;update "output_brazilsforestcode_biomes" set "fcdd_agro00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_agro10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_agro20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_agro30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_agro40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_agro50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_forreg30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_forreg40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_forreg50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_natveg00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_natveg10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_natveg20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_natveg30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_natveg40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_natveg50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_nonprodq00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_nonprodq10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_nonprodq20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_nonprodq30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_nonprodq40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_nonprodq50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_notrel00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_notrel10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_notrel20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_notrel30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_notrel40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_notrel50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_pltfor00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_pltfor10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_pltfor20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_pltfor30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_pltfor40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_pltfor50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_wetlnd00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_wetlnd10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_wetlnd20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_wetlnd30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_wetlnd40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcdd_wetlnd50" = 0.0;commit;
