begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_agro00" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_agro10" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_agro20" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_agro30" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_agro40" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_agro50" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_forreg30" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_forreg40" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_forreg50" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_natveg00" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_natveg10" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_natveg20" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_natveg30" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_natveg40" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_natveg50" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_nonprodq00" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_nonprodq10" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_nonprodq20" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_nonprodq30" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_nonprodq40" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_nonprodq50" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_notrel00" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_notrel10" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_notrel20" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_notrel30" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_notrel40" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_notrel50" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_pltfor00" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_pltfor10" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_pltfor20" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_pltfor30" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_pltfor40" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_pltfor50" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_wetlnd00" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_wetlnd10" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_wetlnd20" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_wetlnd30" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_wetlnd40" numeric;commit;
begin;alter table "output_brazilsforestcode_brazil" add column if not exists "fcnocra_dd_wetlnd50" numeric;commit;

begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro00" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro10" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro20" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro30" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro40" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro50" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_forreg30" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_forreg40" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_forreg50" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg00" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg10" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg20" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg30" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg40" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg50" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq00" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq10" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq20" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq30" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq40" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq50" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel00" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel10" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel20" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel30" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel40" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel50" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor00" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor10" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor20" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor30" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor40" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor50" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd00" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd10" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd20" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd30" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd40" = 0.0;commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd50" = 0.0;commit;

begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro00" = (select trunc(sum("agro00" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro10" = (select trunc(sum("agro10" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro20" = (select trunc(sum("agro20" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro30" = (select trunc(sum("agro30" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro40" = (select trunc(sum("agro40" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_agro50" = (select trunc(sum("agro50" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg00" = (select trunc(sum("natveg00" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg10" = (select trunc(sum("natveg10" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg20" = (select trunc(sum("natveg20" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg30" = (select trunc(sum("natveg30" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg40" = (select trunc(sum("natveg40" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_natveg50" = (select trunc(sum("natveg50" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq00" = (select trunc(sum("nonprodq00" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq10" = (select trunc(sum("nonprodq10" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq20" = (select trunc(sum("nonprodq20" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq30" = (select trunc(sum("nonprodq30" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq40" = (select trunc(sum("nonprodq40" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_nonprodq50" = (select trunc(sum("nonprodq50" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel00" = (select trunc(sum("notrel00" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel10" = (select trunc(sum("notrel10" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel20" = (select trunc(sum("notrel20" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel30" = (select trunc(sum("notrel30" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel40" = (select trunc(sum("notrel40" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_notrel50" = (select trunc(sum("notrel50" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor00" = (select trunc(sum("pltfor00" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor10" = (select trunc(sum("pltfor10" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor20" = (select trunc(sum("pltfor20" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor30" = (select trunc(sum("pltfor30" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor40" = (select trunc(sum("pltfor40" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_pltfor50" = (select trunc(sum("pltfor50" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd00" = (select trunc(sum("wetlnd00" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd10" = (select trunc(sum("wetlnd10" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd20" = (select trunc(sum("wetlnd20" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd30" = (select trunc(sum("wetlnd30" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd40" = (select trunc(sum("wetlnd40" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_wetlnd50" = (select trunc(sum("wetlnd50" ), 3) from "brazilsforestcode_fcnocra_dd");commit;

begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_forreg30" = (select trunc(sum("forreg30" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_forreg40" = (select trunc(sum("forreg40" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
begin;update "output_brazilsforestcode_brazil" set "fcnocra_dd_forreg50" = (select trunc(sum("forreg50" ), 3) from "brazilsforestcode_fcnocra_dd");commit;
