begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_agro00" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_agro10" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_agro20" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_agro30" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_agro40" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_agro50" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_forreg30" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_forreg40" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_forreg50" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_natveg00" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_natveg10" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_natveg20" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_natveg30" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_natveg40" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_natveg50" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_nonprodq00" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_nonprodq10" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_nonprodq20" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_nonprodq30" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_nonprodq40" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_nonprodq50" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_notrel00" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_notrel10" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_notrel20" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_notrel30" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_notrel40" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_notrel50" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_pltfor00" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_pltfor10" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_pltfor20" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_pltfor30" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_pltfor40" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_pltfor50" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_wetlnd00" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_wetlnd10" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_wetlnd20" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_wetlnd30" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_wetlnd40" numeric;commit;
begin;alter table "output_brazilsforestcode_regions" add column if not exists "fcnocra_dd_wetlnd50" numeric;commit;

begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_agro00" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_agro10" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_agro20" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_agro30" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_agro40" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_agro50" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_forreg30" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_forreg40" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_forreg50" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_natveg00" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_natveg10" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_natveg20" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_natveg30" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_natveg40" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_natveg50" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_nonprodq00" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_nonprodq10" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_nonprodq20" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_nonprodq30" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_nonprodq40" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_nonprodq50" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_notrel00" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_notrel10" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_notrel20" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_notrel30" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_notrel40" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_notrel50" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_pltfor00" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_pltfor10" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_pltfor20" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_pltfor30" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_pltfor40" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_pltfor50" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_wetlnd00" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_wetlnd10" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_wetlnd20" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_wetlnd30" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_wetlnd40" = 0.0;commit;
begin;update "output_brazilsforestcode_regions" set "fcnocra_dd_wetlnd50" = 0.0;commit;
