begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_agro00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_agro10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_agro20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_agro30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_agro40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_agro50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_forreg30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_forreg40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_forreg50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_natveg00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_natveg10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_natveg20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_natveg30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_natveg40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_natveg50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_nonprodq00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_nonprodq10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_nonprodq20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_nonprodq30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_nonprodq40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_nonprodq50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_notrel00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_notrel10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_notrel20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_notrel30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_notrel40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_notrel50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_pltfor00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_pltfor10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_pltfor20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_pltfor30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_pltfor40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_pltfor50" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_wetlnd00" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_wetlnd10" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_wetlnd20" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_wetlnd30" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_wetlnd40" numeric;commit;
begin;alter table "output_brazilsforestcode_biomes" add column if not exists "fcnosfa_wetlnd50" numeric;commit;

begin;update "output_brazilsforestcode_biomes" set "fcnosfa_agro00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_agro10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_agro20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_agro30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_agro40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_agro50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_forreg30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_forreg40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_forreg50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_natveg00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_natveg10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_natveg20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_natveg30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_natveg40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_natveg50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_nonprodq00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_nonprodq10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_nonprodq20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_nonprodq30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_nonprodq40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_nonprodq50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_notrel00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_notrel10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_notrel20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_notrel30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_notrel40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_notrel50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_pltfor00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_pltfor10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_pltfor20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_pltfor30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_pltfor40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_pltfor50" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_wetlnd00" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_wetlnd10" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_wetlnd20" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_wetlnd30" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_wetlnd40" = 0.0;commit;
begin;update "output_brazilsforestcode_biomes" set "fcnosfa_wetlnd50" = 0.0;commit;
